### ISSUE TITLE
Build instructions from README currently fail

### ISSUE THREAD

**Issue by prismofeverything** [pluradj/janusgraph-java-example#1]
Hello,

Trying to recreate this (java 8 update 110, maven 3.3.9, macosx 10.11.6) I get the following error on the first step:

    mvn clean package

Results in this error:

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 2.064 s
    [INFO] Finished at: 2017-03-24T10:37:53-07:00
    [INFO] Final Memory: 8M/245M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project java-example: Could not resolve dependencies for project pluradj.janusgraph.example:java-example:jar:0.1: The following artifacts could not be resolved: org.janusgraph:janusgraph-core:jar:0.1.0-SNAPSHOT, org.janusgraph:janusgraph-berkeleyje:jar:0.1.0-SNAPSHOT, org.janusgraph:janusgraph-lucene:jar:0.1.0-SNAPSHOT: Could not find artifact org.janusgraph:janusgraph-core:jar:0.1.0-SNAPSHOT -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Any idea what's wrong? Thanks!

**Comment by pluradj** [comment]
Thanks for the feedback. The build was picking up the janusgraph jars already build from the local repository.
