### ISSUE TITLE
Add GLV connection example

### ISSUE THREAD

**Issue by twilmes** [pluradj/janusgraph-java-example#2]
@pluradj was wondering if you'd be down with me submitting a PR to bump to Janus 0.2.0 and add an additional Java `withRemote` GLV example?

**Comment by twilmes** [comment]
Never mind, I somehow missed we had a JanusGraph examples module. I'll add it there.

**Comment by pluradj** [comment]
@twilmes sure, that'd be fine, but wouldn't it be better if you add a GLV sample in the main JanusGraph repo https://github.com/JanusGraph/janusgraph/tree/master/janusgraph-examples
